/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 37
#define YY_END_OF_BUFFER 38
static yyconst short int yy_acclist[139] =
    {   0,
       32,   32,   38,   36,   37,   35,   36,   37,   34,   37,
       33,   36,   37,   32,   36,   37,   32,   33,   36,   37,
       32,   36,   37,   36,   37,   32,   36,   37,   32,   36,
       37,   32,   36,   37,   32,   36,   37,   32,   36,   37,
       32,   32,   32,   32,   32,   32,   27,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   28,   32,   32,   32,
        1,   32,   32,   26,   16,   32,   32,   24,   17,   20,
       14,   32,   32,   21,   15,   22,    2,   12,   32,   32,
       23,    3,   13,   10,   32,   32,   32,   32,   32,   11,
       18,   31,   32,   31,   32,   32,   32,   32,   32,   19,

        6,   31,   32,   31,   32,   31,   32,   32,   31,   32,
       31,   32,   32,   32,    7,    8,   32,   31,   32,   31,
       32,   25,   32,   32,    9,   31,   32,   31,   32,   31,
       32,   32,    4,   31,   32,    5,   29,   30
    } ;

static yyconst short int yy_accept[307] =
    {   0,
        1,    2,    3,    4,    6,    9,   11,   14,   17,   21,
       24,   26,   29,   32,   35,   38,   41,   41,   42,   43,
       44,   45,   46,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   48,   49,   50,   51,   52,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   54,   55,   56,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   58,   58,
       58,   58,   59,   60,   61,   63,   64,   64,   64,   64,

       64,   64,   64,   64,   64,   64,   64,   64,   64,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   66,   66,   67,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   69,   69,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   71,   72,   72,   72,   72,
       73,   74,   74,   74,   74,   74,   74,   74,   75,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   77,   77,
       78,   79,   80,   81,   81,   81,   81,   81,   81,   82,
       83,   84,   84,   84,   84,   84,   84,   85,   85,   86,
       87,   88,   89,   90,   90,   90,   90,   90,   91,   91,

       91,   92,   92,   92,   92,   94,   96,   97,   98,   99,
      100,  100,  101,  101,  101,  101,  102,  102,  102,  102,
      104,  106,  108,  109,  111,  113,  114,  115,  116,  116,
      116,  116,  117,  117,  117,  118,  120,  122,  124,  125,
      126,  126,  126,  126,  126,  126,  128,  130,  132,  133,
      133,  133,  133,  134,  134,  134,  136,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,

      138,  138,  139,  139,  139,  139
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    5,    8,    8,    5,    5,
        5,    5,    5,    5,    8,    9,   10,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   12,    5,   13,
       14,   15,   16,    5,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
        1,    1,    1,    1,    8,    5,   18,   17,   19,   20,

       21,   22,   23,   24,   25,   17,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   17,    1,    5,    1,    5,    1,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[41] =
    {   0,
        1,    1,    1,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    1,    2,    1,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2
    } ;

static yyconst short int yy_base[321] =
    {   0,
        0,   37,  585,  586,  586,  586,    1,    4,    8,   14,
       65,   13,   23,   27,   30,   43,   17,   38,   50,   51,
       59,   64,   67,   85,  545,   58,  562,  561,   32,  556,
      546,  554,  545,  552,  586,   91,   73,   90,  107,   87,
      101,  555,  554,   52,  549,  539,  547,  538,  545,  541,
      533,  549,  535,  531,  539,  545,  541,  532,  526,  524,
      531,  537,  120,  110,  123,  129,  521,  537,  523,  519,
      527,  533,  529,  520,  514,  512,  519,  525,  517,  522,
      513,  501,  521,  516,  515,  509,  510,  124,  508,  519,
      498,  132,  133,  140,  143,  144,  511,  502,  490,  510,

      505,  504,  498,  499,  509,  496,  507,  486,  147,  497,
      490,  485,  484,  492,  494,  499,  498,  151,  491,  490,
      586,  486,  156,  161,  486,  479,  474,  473,  481,  483,
      488,  487,  586,  480,  586,  476,  164,  478,  468,  476,
      471,  470,  459,  478,  586,  586,  459,  473,  472,  171,
      167,  456,  464,  458,  457,  446,  460,  586,  586,  456,
      443,  421,  416,  393,  384,  373,  388,  586,  349,  586,
      586,  198,  176,  345,  344,  338,  321,  331,  586,  586,
      586,  309,  297,  318,  308,  294,  586,  296,  207,  216,
      181,  223,  188,  280,  300,  285,  271,  586,  276,  279,

      586,  255,  259,  248,  234,  243,  228,  193,  194,  250,
      260,  586,  234,  241,  221,  586,  230,  206,  206,  258,
      267,  276,  281,    0,    0,  285,  289,  586,  215,  194,
      189,  586,  186,  293,  298,  307,  312,  227,  320,  586,
      180,  321,  191,  324,  253,  335,  344,  353,  358,  178,
      330,  254,  586,  349,  362,  370,  586,  366,  375,  378,
      379,  387,  178,  388,  175,  391,  586,  390,  394,  150,
      399,  153,  134,  139,  131,  114,  111,  407,  408,  412,
      413,  419,  420,  423,  424,  427,  428,  431,  432,  435,
      436,  439,  440,  444,  447,  453,  457,  460,  464,  461,

      102,  586,  468,  474,  586,  489,  105,  104,  100,   97,
       84,   81,   70,   49,   44,   43,   33,   28,   24,    7
    } ;

static yyconst short int yy_def[321] =
    {   0,
      306,  306,  305,  305,  305,  305,  307,  308,  308,  308,
      305,  308,  308,  308,  308,  308,  307,  308,  308,  307,
      308,  308,  308,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  308,  308,  308,  308,  308,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  308,  308,  308,  308,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  308,  308,  308,  308,  308,  305,  305,  305,  305,

      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  308,  308,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  309,
      308,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  310,  308,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  310,  311,
      307,  308,  308,  305,  305,  305,  305,  305,  305,  305,

      305,  305,  305,  305,  312,  313,  308,  308,  307,  308,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  312,
      313,  314,  308,  220,  221,  308,  308,  305,  305,  305,
      305,  305,  305,  305,  315,  316,  308,  308,  308,  305,
      305,  305,  305,  305,  305,  317,  316,  314,  308,  305,
      305,  305,  305,  305,  305,  317,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  318,  318,  319,  320,  305,  319,  319,  318,  319,
      320,  305,  305,  319,  319,  320,  318,  320,  319,  305,

      305,  305,  320,  319,    0,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305
    } ;

static yyconst short int yy_nxt[627] =
    {   0,
        4,    5,    6,    7,   17,    9,   19,   20,  290,   22,
       10,   20,   11,   22,    4,   12,   20,   20,   22,   22,
       17,   13,   19,   14,   23,  287,   20,   35,   22,  284,
       20,   15,   22,   20,  256,   22,   16,    4,    5,    6,
        7,   20,    9,   22,  247,  246,   20,   10,   22,   11,
      236,    4,   12,   20,   20,   22,   40,   36,   13,   56,
       14,   37,   20,   39,   22,   38,   57,   20,   15,   22,
       20,  224,   22,   16,   24,   51,   20,   23,   22,   72,
       25,   52,  220,   26,   27,  205,   73,   53,   28,   29,
       20,   30,   22,   20,   20,   22,   22,   31,  189,   32,

       33,  172,   34,   41,   42,   21,   18,   64,   43,   44,
       20,   45,   22,   20,   65,   22,  302,   46,   67,   47,
       48,   63,   49,   20,   68,   22,   20,  118,   22,  118,
       69,   92,   20,  278,   22,   20,   20,   22,   22,   66,
       94,  123,  277,   20,   92,   22,   20,   20,   22,   22,
      137,   92,  137,   93,  118,  276,  118,   95,  275,   20,
      119,   22,   96,  274,   20,  150,   22,  137,  124,  137,
       20,  273,   22,   93,   20,   21,   22,   21,  272,  191,
       21,  192,   21,  138,  191,  271,  207,  119,  268,  193,
      151,  209,  257,  210,  208,  173,  209,  209,  210,  226,

      138,   20,   21,   22,   21,  253,  190,   21,  250,   21,
       20,   21,   22,   21,  243,  190,   21,  242,   21,   20,
       21,   22,   21,  241,  206,   21,  191,   21,  192,  240,
       20,  191,   22,  192,  234,  233,  193,   20,   21,   22,
       21,  193,  221,  222,  232,  223,   20,   21,   22,   21,
      231,  225,  222,  209,  223,  210,  254,  258,  255,  259,
      227,   20,   21,   22,   21,  230,  221,  222,  229,  223,
       20,   21,   22,   21,  228,  225,  222,  219,  223,   20,
       21,   22,  235,  218,   20,   21,   22,   21,  209,  217,
      210,  237,   20,  216,  238,  227,  244,  239,  244,  227,

      215,   20,   21,   22,   21,  214,  245,   21,  213,   21,
       20,   21,   22,   21,  212,   20,  248,   22,   21,  211,
      204,  222,  237,   20,  251,   22,  251,  244,  203,  244,
      249,  202,  201,  251,  252,  251,  200,  245,   20,   21,
       22,   21,  199,  252,   21,  198,   21,   20,   21,   22,
       21,  197,  254,  248,  255,   21,   20,   21,   22,  235,
      196,   20,   21,  238,   21,  254,  239,  255,  249,  258,
      195,  259,  260,   20,   21,   22,   21,  194,  258,   21,
      259,   21,  188,  262,  264,  261,  263,  265,  260,  261,
      266,  269,  266,  269,  266,  262,  266,  269,  263,  269,

      268,  267,  187,  186,  264,  267,  185,  265,  270,  271,
      279,  279,  279,  279,  270,  281,  281,  282,  282,  184,
      280,  280,  283,  283,  285,  285,  286,  289,  288,  291,
      286,  286,  292,  288,  293,  289,  294,  296,  286,  297,
      288,  298,  293,  293,  300,  300,  295,  293,  183,  294,
      286,  299,  288,  182,  301,  301,  297,  181,  298,  295,
      297,  302,  303,  297,  293,  298,  300,  286,  299,  288,
      180,  297,  304,  298,  179,  299,  301,  286,  302,  288,
      178,  177,  176,  299,  175,  174,  171,  170,  302,    8,
        8,  169,  168,  167,  166,  165,  164,  163,  162,  161,

      160,  159,  158,  157,  156,  155,  154,  153,  152,  149,
      148,  147,  146,  145,  144,  143,  142,  141,  140,  139,
      136,  135,  134,  133,  132,  131,  130,  129,  128,  127,
      126,  125,  122,  121,  120,  117,  116,  115,  114,  113,
      112,  111,  110,  109,  108,  107,  106,  105,  104,  103,
      102,  101,  100,   99,   98,   97,   91,   90,   89,   88,
       87,   86,   85,   84,   83,   82,   81,   80,   79,   78,
       77,   76,   75,   74,   71,   70,   62,   61,   60,   59,
       58,   55,   54,   50,  305,    3,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,

      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305
    } ;

static yyconst short int yy_chk[627] =
    {   0,
        1,    1,    1,    1,    7,    1,    7,    8,  320,    8,
        1,    9,    1,    9,    1,    1,   12,   10,   12,   10,
       17,    1,   17,    1,   10,  319,   13,   12,   13,  318,
       14,    1,   14,   15,  317,   15,    1,    2,    2,    2,
        2,   18,    2,   18,  316,  315,   16,    2,   16,    2,
      314,    2,    2,   19,   20,   19,   20,   13,    2,   29,
        2,   14,   21,   16,   21,   15,   29,   22,    2,   22,
       23,  313,   23,    2,   11,   26,   37,   23,   37,   44,
       11,   26,  312,   11,   11,  311,   44,   26,   11,   11,
       40,   11,   40,   38,   36,   38,   36,   11,  310,   11,

       11,  309,   11,   24,   24,  308,  307,   37,   24,   24,
       39,   24,   39,   64,   38,   64,  301,   24,   41,   24,
       24,   36,   24,   63,   41,   63,   65,   88,   65,   88,
       41,   63,   66,  277,   66,   92,   93,   92,   93,   39,
       64,   92,  276,   94,   93,   94,   95,   96,   95,   96,
      109,   94,  109,   63,  118,  275,  118,   65,  274,  123,
       88,  123,   66,  273,  124,  123,  124,  137,   96,  137,
      151,  272,  151,   94,  150,  150,  150,  150,  270,  173,
      150,  173,  150,  109,  191,  265,  191,  118,  263,  173,
      124,  193,  250,  193,  191,  151,  208,  209,  208,  209,

      137,  172,  172,  172,  172,  243,  172,  172,  241,  172,
      189,  189,  189,  189,  233,  189,  189,  231,  189,  190,
      190,  190,  190,  230,  190,  190,  192,  190,  192,  229,
      238,  207,  238,  207,  219,  218,  192,  205,  205,  205,
      205,  207,  205,  205,  217,  205,  206,  206,  206,  206,
      215,  206,  206,  210,  206,  210,  245,  252,  245,  252,
      210,  220,  220,  220,  220,  214,  220,  220,  213,  220,
      221,  221,  221,  221,  211,  221,  221,  204,  221,  222,
      222,  222,  222,  203,  223,  222,  223,  222,  226,  202,
      226,  223,  227,  200,  227,  226,  234,  227,  234,  227,

      199,  235,  235,  235,  235,  197,  234,  235,  196,  235,
      236,  236,  236,  236,  195,  237,  236,  237,  236,  194,
      188,  237,  237,  239,  242,  239,  242,  244,  186,  244,
      239,  185,  184,  251,  242,  251,  183,  244,  246,  246,
      246,  246,  182,  251,  246,  178,  246,  247,  247,  247,
      247,  177,  254,  247,  254,  247,  248,  248,  248,  248,
      176,  249,  248,  249,  248,  255,  249,  255,  249,  258,
      175,  258,  255,  256,  256,  256,  256,  174,  259,  256,
      259,  256,  169,  260,  261,  259,  260,  261,  260,  261,
      262,  264,  262,  264,  266,  268,  266,  269,  268,  269,

      268,  262,  167,  166,  271,  266,  165,  271,  264,  271,
      278,  279,  278,  279,  269,  280,  281,  280,  281,  164,
      278,  279,  282,  283,  282,  283,  284,  285,  284,  285,
      286,  287,  286,  287,  288,  289,  288,  289,  290,  291,
      290,  291,  292,  293,  292,  293,  288,  294,  163,  294,
      295,  291,  295,  162,  292,  293,  296,  161,  296,  294,
      297,  295,  297,  298,  300,  298,  300,  299,  296,  299,
      160,  303,  297,  303,  157,  298,  300,  304,  299,  304,
      156,  155,  154,  303,  153,  152,  149,  148,  304,  306,
      306,  147,  144,  143,  142,  141,  140,  139,  138,  136,

      134,  132,  131,  130,  129,  128,  127,  126,  125,  122,
      120,  119,  117,  116,  115,  114,  113,  112,  111,  110,
      108,  107,  106,  105,  104,  103,  102,  101,  100,   99,
       98,   97,   91,   90,   89,   87,   86,   85,   84,   83,
       82,   81,   80,   79,   78,   77,   76,   75,   74,   73,
       72,   71,   70,   69,   68,   67,   62,   61,   60,   59,
       58,   57,   56,   55,   54,   53,   52,   51,   50,   49,
       48,   47,   46,   45,   43,   42,   34,   33,   32,   31,
       30,   28,   27,   25,    3,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,

      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#define INITIAL 0
#line 3 "lex.l"
#include <stdio.h>
#line 634 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 38 "lex.l"

#line 787 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 306 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 586 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 39 "lex.l"
{quit(); return 0;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 40 "lex.l"
{printf("-Apertura de titulo: %s\n", yytext);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 41 "lex.l"
{printf("-Clausura de titulo: %s\n", yytext);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 42 "lex.l"
{printf("-Apertura de descripcion: %s\n", yytext);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 43 "lex.l"
{printf("-Clausura de descripcion: %s\n", yytext);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 44 "lex.l"
{printf("-Apertura de categoria: %s\n", yytext);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 45 "lex.l"
{printf("-Clausura de categoria: %s\n", yytext);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 46 "lex.l"
{printf("-Apertura de copyright: %s\n", yytext);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 47 "lex.l"
{printf("-Clausura de copyright: %s\n", yytext);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 48 "lex.l"
{printf("-Apertura de alto: %s\n", yytext);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 49 "lex.l"
{printf("-Clausura de alto: %s\n", yytext);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 50 "lex.l"
{printf("-Apertura de ancho: %s\n", yytext);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 51 "lex.l"
{printf("-Clausura de ancho: %s\n", yytext);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 52 "lex.l"
{printf("-Apertura de link: %s\n", yytext);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 53 "lex.l"
{printf("-Clausura de link: %s\n", yytext);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 54 "lex.l"
{printf("-Apertura de url: %s\n", yytext);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 55 "lex.l"
{printf("-Clausura de url: %s\n", yytext);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 56 "lex.l"
{printf("-Apertura de canal: %s\n", yytext);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 57 "lex.l"
{printf("-Clausura de canal: %s\n", yytext);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 58 "lex.l"
{printf("-Apertura de item: %s\n", yytext);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 59 "lex.l"
{printf("-Clausura de item: %s\n", yytext);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 60 "lex.l"
{printf("-Apertura de imagen: %s\n", yytext);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 61 "lex.l"
{printf("-Clausura de imagen: %s\n", yytext);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 62 "lex.l"
{printf("-Clausura de documento RSS: %s\n", yytext);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 63 "lex.l"
{printf("-Version: %s\n", yytext);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 64 "lex.l"
{printf("-Apertura XML: %s\n", yytext);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 65 "lex.l"
{printf("-Clausura XML: %s\n", yytext);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 66 "lex.l"
{printf("-Apertura RSS: %s\n", yytext);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 67 "lex.l"
{printf("-Apertura de documento RSS: %s\n", yytext);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 68 "lex.l"
{printf("-Definicion XML: %s\n", yytext);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 69 "lex.l"
{printf("-Enlace: %s\n", yytext);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 70 "lex.l"
{printf("-Cadena de caracteres: %s\n", yytext);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 71 "lex.l"
{;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 72 "lex.l"
{;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 73 "lex.l"
{;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 74 "lex.l"
{printf("-Sentencia no reconocida: %s\n", yytext);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 75 "lex.l"
ECHO;
	YY_BREAK
#line 1063 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 306 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 306 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 305);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 75 "lex.l"


// Abre archivo o permite el ingreso manual
int main (int argc, char *argv[]){
    if (argc == 2){
        if ( (yyin = fopen(argv[1], "rt")) == NULL){
            printf ("\nNo se puede abrir el archivo (%s)\n", argv[1]);
            return 1;
        } else{
            printf("\nArchivo (%s) abierto.\n", argv[1]);
            yylex();
        }
        printf ("\nFin del archivo (%s)\n", argv[1]);
        fclose(yyin);
        return 0;
    } else{
        yyin = stdin;
        printf ("\nIngrese manualmente las sentencias. Escriba quit para salir\n");
        yylex();
    }
}
quit(){
    printf("Saliendo\n");
}